[config]
reload_apps = true

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/theme.css'
reload_command = 'pkill -USR2 waybar'

[templates.eww]
input_path = '~/.config/matugen/templates/eww.scss'
output_path = '~/.config/eww/colors.scss'
reload_command = 'eww reload'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'
