env = WAYLAND_DISPLAY,wayland-1

gpu-buffers = 2

focus_follows_mouse = yes
focus_on_window_activate = click

general {
    gaps_in = 5
    gaps_out = 20
    border_size = 2
    col.active_border   = rgb(5f88cf)
    col.inactive_border = rgb(1B1F3A)
    resize_on_border = false
    allow_tearing    = false
    layout           = dwindle
}

decoration {
    rounding       = 10
    rounding_power = 2
    active_opacity   = 1.0
    inactive_opacity = 1.0
    shadow {
        enabled      = true
        range        = 4
        render_power = 3
        color        = rgba(1a1a1aee)
    }
    blur {
        enabled   = true
        size      = 8
	# was 3
        passes    = 2
	# was 1
        vibrancy  = 0.1696
	new_optimizations = true    
}
}

animations {
    enabled = true
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows,     1, 7, myBezier
    animation = windowsOut,  1, 7, default, popin 80%
    animation = border,      1, 10, default
    animation = borderangle, 1, 8,  default
    animation = fade,        1, 7,  default
    animation = workspaces,  1, 6,  default
    animation = layers,      1, 6,  default, slide
}

dwindle {
    pseudotile     = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper  = 0
    disable_hyprland_logo    = true
    disable_splash_rendering = true
    vrr = 0
    vfr = true
}

render { direct_scanout = false }
debug  { disable_logs   = false }

source = ~/.config/hypr/conf.d/*.conf
