exec-once = waybar & hyprpaper
exec-once = echo -1000 > /proc/self/oom_score_adj
exec-once = ~/.config/nwg-dock-hyprland/launch.sh
exec-once = eww daemon

exec-once = python /home/samedy/.local/bin/controller-wofi.py
