# MAIN binds
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

# IPAD binds
bind = SUPER ALT, 1, workspace, 11
bind = SUPER ALT, 2, workspace, 12
bind = SUPER ALT, 3, workspace, 13
bind = SUPER ALT, 4, workspace, 14
bind = SUPER ALT, 5, workspace, 15
bind = SUPER ALT, 6, workspace, 16
bind = SUPER ALT, 7, workspace, 17
bind = SUPER ALT, 8, workspace, 18
bind = SUPER ALT, 9, workspace, 19
bind = SUPER ALT, 0, workspace, 20

# move windows
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

bind = SUPER SHIFT ALT, 1, movetoworkspace, 11
bind = SUPER SHIFT ALT, 2, movetoworkspace, 12
bind = SUPER SHIFT ALT, 3, movetoworkspace, 13
bind = SUPER SHIFT ALT, 4, movetoworkspace, 14
bind = SUPER SHIFT ALT, 5, movetoworkspace, 15
bind = SUPER SHIFT ALT, 6, movetoworkspace, 16
bind = SUPER SHIFT ALT, 7, movetoworkspace, 17
bind = SUPER SHIFT ALT, 8, movetoworkspace, 18
bind = SUPER SHIFT ALT, 9, movetoworkspace, 19
bind = SUPER SHIFT ALT, 0, movetoworkspace, 20
