# windowrule = no_blur, class:^(zoom)$

layerrule = blur on, match:namespace rofi

windowrule = float true, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = size 400 500, match:class ^(org.pulseaudio.pavucontrol)$
windowrule = move 1510 50, match:class ^(org.pulseaudio.pavucontrol)$