-- Spotify tray configuration (originally generated by spotify-tray-setup).
-- Loaded after conf/keybinds.lua, so binds here win.

-- NOTE: ~/.config/hypr/UserScripts/smart-close.sh does not exist on this system,
-- so this bind is currently a no-op. Create the script or drop this bind.
hl.bind("SUPER + J", hl.dsp.exec_cmd("~/.config/hypr/UserScripts/smart-close.sh"))

-- Move the active window to the spotify scratchpad without following it.
hl.bind("SUPER + M", hl.dsp.window.move({ workspace = "special:spotify", follow = false }))

hl.bind("SUPER + grave", hl.dsp.workspace.toggle_special("spotify"))
