$mainMonitor = HDMI-A-1
$ipadMonitor = ipad

workspace = 41, persistent
workspace = 41, defaultName:O

# MAIN workspaces
workspace = 1, monitor:$mainMonitor
workspace = 2, monitor:$mainMonitor
workspace = 3, monitor:$mainMonitor
workspace = 4, monitor:$mainMonitor
workspace = 5, monitor:$mainMonitor
workspace = 6, monitor:$mainMonitor
workspace = 7, monitor:$mainMonitor
workspace = 8, monitor:$mainMonitor
workspace = 9, monitor:$mainMonitor
workspace = 10, monitor:$mainMonitor

# IPAD workspaces
workspace = 11, monitor:$ipadMonitor
workspace = 12, monitor:$ipadMonitor
workspace = 13, monitor:$ipadMonitor
workspace = 14, monitor:$ipadMonitor
workspace = 15, monitor:$ipadMonitor
workspace = 16, monitor:$ipadMonitor
workspace = 17, monitor:$ipadMonitor
workspace = 18, monitor:$ipadMonitor
workspace = 19, monitor:$ipadMonitor
workspace = 20, monitor:$ipadMonitor

# optional: prevent jumping
workspace = 1, persistent:true
workspace = 11, persistent:true
